### ISSUE TITLE
NullPointerException org.pac4j.play.PlayWebContext.getRequestParameters

### ISSUE THREAD

**Issue by schmielinski** [pac4j/play-pac4j#225]
Hi,
I'm having this issue after updating from 4.0.0 to 4.1.0. In PlayWebContext.getRequestParameters you use
request.hasBody() condition which returns true but my body is null. So thats why request.body().asFormUrlEncoded() throws NullPointerException

Stacktrace:
Caused by: java.lang.NullPointerException
	at org.pac4j.play.PlayWebContext.getRequestParameters(PlayWebContext.java:160)
	at org.pac4j.play.PlayWebContext.getRequestParameter(PlayWebContext.java:146)
	at org.pac4j.core.client.finder.DefaultClientFinder.find(DefaultClientFinder.java:28)
	at org.pac4j.core.engine.DefaultSecurityLogic.perform(DefaultSecurityLogic.java:96)

EDIT: The problem appears only when I'm using SecurityFilter. Protecting urls by @Secure annotation works fine

**Comment by leleuj** [comment]
OK. I will fix that onthe  3.1.1 and 4.1.1 versions as soon as possible...

**Comment by leleuj** [comment]
In fact, the problem does not happen on the 3.1.0. Only for 4.1.0.

It should be fixed in 4.1.1-SNAPSHOT: @schmielinski can you confirm it's ok? Thanks

**Comment by schmielinski** [comment]
Yes, now it's ok. Thanks for quick fix

**Comment by leleuj** [comment]
Thanks for your feedback. I'm releasing the version 4.1.1...
