### ISSUE TITLE
NullPointerException oidc callback

### ISSUE THREAD

**Issue by marcadella** [pac4j/play-pac4j#264]
I get a null pointer exception in the call back from an oidc request.
Below is the debug printouts including the stacktrace of the exception.
It is `idToken` that is null and the reason is because my OIDC provider doesn not return any id_token. The question is whether pac4j-oidc is a bit too strict and should let a token endpoint return only an access_token?

```
[debug] o.p.c.e.DefaultCallbackLogic - === CALLBACK ===
[debug] o.p.c.c.f.DefaultCallbackClientFinder - result: [OidcClient]
[debug] o.p.c.e.DefaultCallbackLogic - foundClient: #OidcClient# | name: OidcClient | callbackUrl: http://localhost:9000/callback | callbackUrlResolver: org.pac4j.core.http.callback.QueryParameterCallbackUrlResolver@2a492ef4 | ajaxRequestResolver: org.pac4j.core.http.ajax.DefaultAjaxRequestResolver@1422208d | redirectActionBuilder: org.pac4j.oidc.redirect.OidcRedirectActionBuilder@2fbc45a0 | credentialsExtractor: org.pac4j.oidc.credentials.extractor.OidcExtractor@60f87f6a | authenticator: org.pac4j.oidc.credentials.authenticator.OidcAuthenticator@3a5c30f | profileCreator: org.pac4j.oidc.profile.creator.OidcProfileCreator@686adbe | logoutActionBuilder: org.pac4j.oidc.logout.OidcLogoutActionBuilder@4b5a798b | authorizationGenerators: [controllers.RoleAdminAuthGenerator@68fa5ca5] | configuration: #OidcConfiguration# | clientId: 80d63772-7f61-4f3b-b5d5-839bbd17d34f | secret: [protected] | discoveryURI: https://login.elixir-czech.org/oidc/.well-known/openid-configuration | scope: openid profile email | customParams: {prompt=consent} | clientAuthenticationMethod: null | useNonce: false | preferredJwsAlgorithm: null | maxAge: null | maxClockSkew: 30 | connectTimeout: 500 | readTimeout: 5000 | resourceRetriever: com.nimbusds.jose.util.DefaultResourceRetriever@456a470e | responseType: code | responseMode: null | logoutUrl: null | withState: false | stateGenerator: org.pac4j.core.state.StaticOrRandomStateGenerator@76b2e940 | |
[debug] o.p.o.c.e.OidcExtractor - Authentication response successful
[debug] o.p.o.c.a.OidcAuthenticator - Token response: status=200, content={"access_token":"eyJqa3UiOiJodHRwczpcL1wvbG9naW4uZWxpeGlyLWN6ZWNoLm9yZ1wvb2lkY1wvandrIiwia2lkIjoicnNhMSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiI0NzEzOSIsImF6cCI6IjgwZDYzNzcyLTdmNjEtNGYzYi1iNWQ1LTgzOWJiZDE3ZDM0ZiIsInNjb3BlIjoiIiwiaXNzIjoiaHR0cHM6XC9cL2xvZ2luLmVsaXhpci1jemVjaC5vcmdcL29pZGNcLyIsImV4cCI6MTU2MzE5MzQ5NiwiaWF0IjoxNTYzMTg5ODk2LCJqdGkiOiJiNTA5MGEyNS0zZjBjLTQ5YTktODk4My0xMDRjOTNhMzMwMTYifQ.rLr8tKERNLhirf4Lkj8WveZh99PEk4WrLnI6OvR-9U1ucpUxMkX2Ls0I35bXdJ1iipuFwr04Ncb4nLVIx0MmH08olFWV_YIt376lz-pQR_mAr2zQ9oVOPZkTXIljlMGU-lqOMxD8MKWsN3h-wvFQOB2bqcmaZ22ZKhebkMLXyX7AuaffP204qvw9o8Jr7QgQLPEoUnEWP9-9GGlK5UjYTGMG82MIQU9_w8iFfWx8LQewyhLCjsF90UcGVbJe8j9UpE4Gv3YG-ZDcZk5kvEf46IXB9tPqtcDGG0Z9i6GGiJVAh8yoeVphD9NVA3GqlMUw9GO_s32AfT51eNb3GTlM6A","token_type":"Bearer","expires_in":3599}

[debug] o.p.o.c.a.OidcAuthenticator - Token response successful
[debug] o.p.o.c.OidcClient - Credentials validation took: 397 ms
[debug] o.p.c.e.DefaultCallbackLogic - credentials: #OidcCredentials# | code: XmdaSNzLY0SvOPAEDfwucZ | accessToken: eyJqa3UiOiJodHRwczpcL1wvbG9naW4uZWxpeGlyLWN6ZWNoLm9yZ1wvb2lkY1wvandrIiwia2lkIjoicnNhMSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiI0NzEzOSIsImF6cCI6IjgwZDYzNzcyLTdmNjEtNGYzYi1iNWQ1LTgzOWJiZDE3ZDM0ZiIsInNjb3BlIjoiIiwiaXNzIjoiaHR0cHM6XC9cL2xvZ2luLmVsaXhpci1jemVjaC5vcmdcL29pZGNcLyIsImV4cCI6MTU2MzE5MzQ5NiwiaWF0IjoxNTYzMTg5ODk2LCJqdGkiOiJiNTA5MGEyNS0zZjBjLTQ5YTktODk4My0xMDRjOTNhMzMwMTYifQ.rLr8tKERNLhirf4Lkj8WveZh99PEk4WrLnI6OvR-9U1ucpUxMkX2Ls0I35bXdJ1iipuFwr04Ncb4nLVIx0MmH08olFWV_YIt376lz-pQR_mAr2zQ9oVOPZkTXIljlMGU-lqOMxD8MKWsN3h-wvFQOB2bqcmaZ22ZKhebkMLXyX7AuaffP204qvw9o8Jr7QgQLPEoUnEWP9-9GGlK5UjYTGMG82MIQU9_w8iFfWx8LQewyhLCjsF90UcGVbJe8j9UpE4Gv3YG-ZDcZk5kvEf46IXB9tPqtcDGG0Z9i6GGiJVAh8yoeVphD9NVA3GqlMUw9GO_s32AfT51eNb3GTlM6A | refreshToken: null | idToken: null |
[debug] o.p.o.c.OidcClient - credentials : #OidcCredentials# | code: XmdaSNzLY0SvOPAEDfwucZ | accessToken: eyJqa3UiOiJodHRwczpcL1wvbG9naW4uZWxpeGlyLWN6ZWNoLm9yZ1wvb2lkY1wvandrIiwia2lkIjoicnNhMSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiI0NzEzOSIsImF6cCI6IjgwZDYzNzcyLTdmNjEtNGYzYi1iNWQ1LTgzOWJiZDE3ZDM0ZiIsInNjb3BlIjoiIiwiaXNzIjoiaHR0cHM6XC9cL2xvZ2luLmVsaXhpci1jemVjaC5vcmdcL29pZGNcLyIsImV4cCI6MTU2MzE5MzQ5NiwiaWF0IjoxNTYzMTg5ODk2LCJqdGkiOiJiNTA5MGEyNS0zZjBjLTQ5YTktODk4My0xMDRjOTNhMzMwMTYifQ.rLr8tKERNLhirf4Lkj8WveZh99PEk4WrLnI6OvR-9U1ucpUxMkX2Ls0I35bXdJ1iipuFwr04Ncb4nLVIx0MmH08olFWV_YIt376lz-pQR_mAr2zQ9oVOPZkTXIljlMGU-lqOMxD8MKWsN3h-wvFQOB2bqcmaZ22ZKhebkMLXyX7AuaffP204qvw9o8Jr7QgQLPEoUnEWP9-9GGlK5UjYTGMG82MIQU9_w8iFfWx8LQewyhLCjsF90UcGVbJe8j9UpE4Gv3YG-ZDcZk5kvEf46IXB9tPqtcDGG0Z9i6GGiJVAh8yoeVphD9NVA3GqlMUw9GO_s32AfT51eNb3GTlM6A | refreshToken: null | idToken: null |
[warn] o.p.o.p.c.TokenValidator - Preferred JWS algorithm: null not available. Using all metadata algorithms: [HS256, HS384, HS512, RS256, RS384, RS512, ES256, ES384, ES512, PS256, PS384, PS512, none]
[debug] o.p.o.p.OidcProfile - adding => key: access_token / value: eyJqa3UiOiJodHRwczpcL1wvbG9naW4uZWxpeGlyLWN6ZWNoLm9yZ1wvb2lkY1wvandrIiwia2lkIjoicnNhMSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiI0NzEzOSIsImF6cCI6IjgwZDYzNzcyLTdmNjEtNGYzYi1iNWQ1LTgzOWJiZDE3ZDM0ZiIsInNjb3BlIjoiIiwiaXNzIjoiaHR0cHM6XC9cL2xvZ2luLmVsaXhpci1jemVjaC5vcmdcL29pZGNcLyIsImV4cCI6MTU2MzE5MzQ5NiwiaWF0IjoxNTYzMTg5ODk2LCJqdGkiOiJiNTA5MGEyNS0zZjBjLTQ5YTktODk4My0xMDRjOTNhMzMwMTYifQ.rLr8tKERNLhirf4Lkj8WveZh99PEk4WrLnI6OvR-9U1ucpUxMkX2Ls0I35bXdJ1iipuFwr04Ncb4nLVIx0MmH08olFWV_YIt376lz-pQR_mAr2zQ9oVOPZkTXIljlMGU-lqOMxD8MKWsN3h-wvFQOB2bqcmaZ22ZKhebkMLXyX7AuaffP204qvw9o8Jr7QgQLPEoUnEWP9-9GGlK5UjYTGMG82MIQU9_w8iFfWx8LQewyhLCjsF90UcGVbJe8j9UpE4Gv3YG-ZDcZk5kvEf46IXB9tPqtcDGG0Z9i6GGiJVAh8yoeVphD9NVA3GqlMUw9GO_s32AfT51eNb3GTlM6A / class com.nimbusds.oauth2.sdk.token.BearerAccessToken
[error] application - 

! @7cg6abnf9 - Internal server error, for (GET) [/callback?client_name=OidcClient&code=XmdaSNzLY0SvOPAEDfwucZ&state=yXECjXSUiHz2DcERmzMGFxkXeFNVPT2bTr2rHg6KQvM] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[CompletionException: java.lang.NullPointerException]]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:351)
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:267)
        at play.core.server.AkkaHttpServer$$anonfun$1.applyOrElse(AkkaHttpServer.scala:382)
        at play.core.server.AkkaHttpServer$$anonfun$1.applyOrElse(AkkaHttpServer.scala:380)
        at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:417)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
Caused by: java.util.concurrent.CompletionException: java.lang.NullPointerException
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
        at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:79)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.NullPointerException: null
        at org.pac4j.oidc.profile.creator.OidcProfileCreator.create(OidcProfileCreator.java:74)
        at org.pac4j.oidc.profile.creator.OidcProfileCreator.create(OidcProfileCreator.java:40)
        at org.pac4j.core.client.BaseClient.retrieveUserProfile(BaseClient.java:113)
        at org.pac4j.core.client.BaseClient.getUserProfile(BaseClient.java:93)
        at org.pac4j.core.engine.DefaultCallbackLogic.perform(DefaultCallbackLogic.java:92)
        at org.pac4j.play.CallbackController.lambda$callback$0(CallbackController.java:56)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
        at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:79)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
```

**Comment by marcadella** [comment]
This is a pac4j-oidc issue, not a play-pac4j
