### ISSUE TITLE
PlayCookieSessionStore doesn't handle incompatible data

### ISSUE THREAD

**Issue by mabrcosta** [pac4j/play-pac4j#330]
After upgrading from version 7 to 10 we've been having errors with this logged stacktrace:
```
play.api.UnexpectedException: Unexpected exception[NullPointerException: null]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:331)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:253)
	at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:424)
	at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:420)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:453)
Caused by: java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:203)
	at java.util.Optional.<init>(Optional.java:96)
	at java.util.Optional.of(Optional.java:108)
	at org.pac4j.play.store.PlayCookieSessionStore.get(PlayCookieSessionStore.java:62)
	at org.pac4j.play.store.PlayCookieSessionStore.get(PlayCookieSessionStore.java:29)
2020-04-24 12:47:03,068 [application-akka.actor.default-dispatcher-185] WARN  o.p.c.u.JavaSerializationHelper - cannot Java deserialize object
java.io.InvalidClassException: org.pac4j.core.profile.UserProfile; local class incompatible: stream classdesc serialVersionUID = 9020114478664816338, local class serialVersionUID = 162816877730751610
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:699)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1885)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1751)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1885)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1751)
```
As the stacktrace points, this is caused by the stored cookie session data not being compatible between the two versions due to the java serialization. 

A simple solution could be changing `PlayCookieSessionStore` line 62 from `return Optional.of(value);` to `return Optional.ofNullable(value);` and letting the remaining logic reauthenticate the user.

For now, as a workaround to the issue, we've changed the session cookie name to a new one, forcing reauthentication with correct data values.

**Comment by leleuj** [comment]
Thanks for reporting. It should be fixed in version 10.0.1-SNAPSHOT: can you try and confirm? Thx

**Comment by mabrcosta** [comment]
Apologies for the late response. While it solved the original problem it appears there's still some data inconsistency when it goes for the re-authentication step.

```
Caused by: org.pac4j.core.exception.TechnicalException: State parameter is different from the one sent in authentication request. Session expired or possible threat of cross-site request forgery
	at org.pac4j.oidc.credentials.extractor.OidcExtractor.extract(OidcExtractor.java:101)
	at org.pac4j.core.client.BaseClient.retrieveCredentials(BaseClient.java:61)
	at org.pac4j.core.client.IndirectClient.getCredentials(IndirectClient.java:140)
	at org.pac4j.core.engine.DefaultCallbackLogic.perform(DefaultCallbackLogic.java:81)
	at org.pac4j.play.CallbackController.lambda$callback$0(CallbackController.java:54)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)

```
On my particular case I noted that cookie attempting to be set just before the redirect is way beyond the allowed cookie size limit, at around 6.9kB. The existing cookie (set by the legacy version, 7.0 in my case) was already near it, at 3.9kB.

**Comment by leleuj** [comment]
This is very strange. I kept the original algorithm and the renamed `removeLoginData` method should now remove the ID token thus the final cookie size should be smaller.

I will investigate.

**Comment by leleuj** [comment]
I cannot reproduce your issue.

Testing the play-pac4j-scala demo v7, I have:
- profile serialized: 2456 bytes, cookie size: 3976 bytes

With v10, I have:
- profile serialized: 1348 bytes, cookie size: 2744 bytes

Exactly, the behavior I expected.

Can you investigate on your side?
