### ISSUE TITLE
JavaSerializationHelper: invalid class exception

### ISSUE THREAD

**Issue by petahathub** [pac4j/play-pac4j#362]
Hi,

I have updated in Play framework 2.7. from play-pac4j 8.0.1 to 9.0.2 with pac4j-sql from 3.7. to 4.1. I use DbProfile with serialization: storageAttributes.put(SERIALIZED_PROFILE, javaSerializationHelper.serializeToBase64(profile)) in AbstractProfileService. Serialized profile is stored in database. It worked well.

But after update to 9.0.2 deserialization ends with exception:

```
[WARN] from org.pac4j.core.util.JavaSerializationHelper in application-akka.actor.default-dispatcher-17 - cannot Java deserialize object
java.io.InvalidClassException: org.pac4j.core.profile.UserProfile; local class incompatible: stream classdesc serialVersionUID = 9020114478664816338, local class serialVersionUID = 162816877730751610
	at java.base/java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:689)
	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1903)
	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1772)
	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1903)
	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1772)
	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1903)
	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1772)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2060)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:430)
	at org.pac4j.core.util.JavaSerializationHelper.deserializeFromBytes(JavaSerializationHelper.java:82)
	at org.pac4j.core.util.JavaSerializationHelper.deserializeFromBase64(JavaSerializationHelper.java:69)
	at security.IndirectKerberosClientConfable.retrieveCredentials(IndirectKerberosClientConfable.java:85)
	at org.pac4j.core.client.IndirectClient.getCredentials(IndirectClient.java:143)
	at org.pac4j.core.engine.DefaultCallbackLogic.perform(DefaultCallbackLogic.java:85)
	at org.pac4j.play.CallbackController.lambda$callback$0(CallbackController.java:54)
```

There were changes in UserProfile, so DbProfile saved thru DbProfileService cannot be loaded back:

```
        DbProfileService profileService = new DbProfileService(db.getDataSource(), new JBCryptPasswordEncoder(BCrypt.gensalt()));
        DbProfile dbProfile;
        
        if (data.getId() == null) {
            ...
            dbProfile = new DbProfile();
        } else {
            dbProfile = profileService.findById(data.getId().toString());
        }
        dbProfile.setRemembered(false);
        dbProfile.setClientName(data.getFirstname() + " " + data.getLastname());

        dbProfile.addAttribute("username", data.getUsername());
       ...

        if (data.getRoles() != null) {
            dbProfile.setRoles(new HashSet<>(data.getRoles()));
        } else {
            dbProfile.setRoles(Collections.emptySet());
        }

        if (data.getId() == null) {
            profileService.create(dbProfile, pswd);
        } else {
            profileService.update(dbProfile, null);
        }
```

I am authenticated by company windows spnego-kerberos and retrieved credentials are compared with local application database:
```
        Optional<UserProfile> optProfile = getUserProfile(credentials.get(), context);
        KerberosProfile profile = (KerberosProfile) optProfile.orElseThrow(() -> UnauthorizedAction.INSTANCE);

        String clientName = profile.getId().toLowerCase();
        clientName = clientName.substring(0, clientName.indexOf("@"));

        AcUserEntity loggedUser = AcUserEntity.find....where().eq("clientname", clientName)
                ...
        if (loggedUser == null) {
            throw UnauthorizedAction.INSTANCE;
        }

        final DbProfile serProfile = (DbProfile) javaSerializationHelper.deserializeFromBase64(
                loggedUser.getSerializedprofile() => **NULL**
        );
```

**Comment by leleuj** [comment]
Indeed, the `UserProfile` is an abstract class in v3.x and an interface in v4.x. And it may change again in v5.x.

This is when I realized that it was a bad idea to store the user profile as a Java serialized data.

I will think about it and try to figure out some solution...

**Comment by leleuj** [comment]
The solution is ready for tests. Instead of using the Java serialization, I use the JSON format.

So you can use v3.9.0-SNAPSHOT and v4.2.0-SNAPSHOT for that. These versions are able to read Java serialized data as well as JSON and write in JSON.

So for example if you use v3.9.0-SNAPSHOT and create new profiles in database, you'll able to read them with v4.2.0-SNAPSHOT while you won't be able to read others.
To migrate the data, you need to use the `ProfileServiceSerializer`, read the `serializedprofile` column, decode it as a profile, encode it as a string and update it in the database.

I'll cut the releases as soon as you confirm it work for you. Thanks

**Comment by petahathub** [comment]
Hi,

I have dependencies:

libraryDependencies += "org.pac4j" %% "play-pac4j" % "8.0.2"
libraryDependencies += "org.pac4j" % "pac4j" % "3.9.0-SNAPSHOT"
libraryDependencies += "org.pac4j" % "pac4j-sql" % "3.9.0-SNAPSHOT"
libraryDependencies += "org.pac4j" % "pac4j-http" % "3.9.0-SNAPSHOT"
libraryDependencies += "org.pac4j" % "pac4j-kerberos" % "3.9.0-SNAPSHOT" exclude ("org.springframework","spring-core")

and yes, the following works well:

```
   ProfileServiceSerializer serializer = new ProfileServiceSerializer(DbProfile.class);
   DbProfile serProfile = (DbProfile) serializer.decode(loggedUser.getSerializedprofile());  // serialized in 3.7.
   String json = serializer.encode(serProfile);
   DbProfile testProfile = (DbProfile) serializer.decode(json);
```

**Comment by leleuj** [comment]
Good! I will cut the releases soon.

**Comment by leleuj** [comment]
The releases v3.9.0 and v4.2.0 are now available.
