### ISSUE TITLE
11.0.0-PLAY2.8-RC2 seems to delete play session cookie on OIDC redirect.

### ISSUE THREAD

**Issue by ndmckinley** [pac4j/play-pac4j#390]
Hi,

I'm using pac4j 5.0.0-RC2, Play 2.8, and play-pac4j 11.0.0-PLAY2.8-RC2.  I am unable to complete an OIDC login with a nonce, because when I return from authenticating with the OIDC provider, my play session cookie is gone.

It seems like a recurrence of #144.

Here you can see it happening in the trace logs:

## Request to the page that redirects me to the login server

```
play   | [debug] o.p.p.s.PlayCookieSessionStore - set key: OidcClient$nonceSessionParameter, with value: 3CTD9eQkxQ8B_rEQ3nmqlsFCeuM0Dx9xWCWyc1WSEog                             
play   | [debug] o.p.o.r.OidcRedirectionActionBuilder - Authentication request url: https://idcs-f582fefb879b4db5a88a370e8f2f6013.identity.oraclecloud.com/oauth2/v1/a[1058/3660$
ope=openid+profile+email&response_type=id_token&redirect_uri=http%3A%2F%2Flocalhost%3A9000%2Fcallback%2FOidcClient&nonce=3CTD9eQkxQ8B_rEQ3nmqlsFCeuM0Dx9xWCWyc1WSEog&client_id=<snip>&response_mode=form_post                                                                                                                           
play   | [debug] o.p.p.h.PlayHttpActionAdapter - requires HTTP action: 302                                                                                                       
play   | [info] loggingfilter - GET     /users/me       295ms   302                                                                                                              
play   | [trace] loggingfilter - request cookies: key: PLAY_SESSION, value: <snip for length, but it decodes to a valid cookie>                                                                                                                                                            
play   | key: pac4jCsrfToken, value: 904a148b6e9d4cae9688759bbba2397b                                                                                                            
play   |                                                                                                                                                                         
play   | [trace] loggingfilter - response headers: {Cache-Control=no-cache, no-store, max-age=0, must-revalidate, Expires=0, Location=https://idcs-f582fefb879b4db5a88a370e8f2f60
13.identity.oraclecloud.com/oauth2/v1/authorize?scope=openid+profile+email&response_type=id_token&redirect_uri=http%3A%2F%2Flocalhost%3A9000%2Fcallback%2FOidcClient&nonce=3CTD9e
QkxQ8B_rEQ3nmqlsFCeuM0Dx9xWCWyc1WSEog&client_id=<snip>&response_mode=form_post, Pragma=no-cache, X-Content-Type-Options=nosniff, X-Frame-Options=DENY, 
X-XSS-Protection=1; mode=block}                                                                                                                                                  
play   | [trace] loggingfilter - response body:                                                                                                                                  
play   | [trace] loggingfilter - response cookies: key: pac4jCsrfToken, value: 1735d195c6f84e859ae50c014e230560                                                                  
```
## callback

```
play   | [debug] o.p.c.e.DefaultCallbackLogic - === CALLBACK ===                                                                                                                 
play   | [debug] o.p.c.u.InitializableObject - Initializing: GuestClient                                                                                                         
play   | [debug] o.p.c.u.InitializableObject - Initializing: FakeAdminClient                                                                                                     
play   | [debug] o.p.c.c.f.DefaultCallbackClientFinder - result: [OidcClient]                                                                                                    
play   | [debug] o.p.c.e.DefaultCallbackLogic - foundClient: #OidcClient# | name: OidcClient | callbackUrl: http://localhost:9000/callback | callbackUrlResolver: org.pac4j.core.
http.callback.PathParameterCallbackUrlResolver@4565a786 | ajaxRequestResolver: org.pac4j.core.http.ajax.DefaultAjaxRequestResolver@69843726 | redirectionActionBuilder: org.pac4j
.oidc.redirect.OidcRedirectionActionBuilder@39183d9d | credentialsExtractor: org.pac4j.oidc.credentials.extractor.OidcExtractor@4120efa9 | authenticator: org.pac4j.oidc.credenti
als.authenticator.OidcAuthenticator@253f848d | profileCreator: org.pac4j.oidc.profile.creator.OidcProfileCreator@6dcaaa0b | logoutActionBuilder: org.pac4j.oidc.logout.OidcLogout
ActionBuilder@15c686fa | authorizationGenerators: [] | configuration: #OidcConfiguration# | clientId: <snip, but, correct> | secret: [protected] | discoveryURI: 
https://idcs-f582fefb879b4db5a88a370e8f2f6013.identity.oraclecloud.com/.well-known/openid-configuration | scope: null | customParams: {} | clientAuthenticationMethod: null | useNonc
e: true | preferredJwsAlgorithm: null | maxAge: null | maxClockSkew: 30 | connectTimeout: 500 | readTimeout: 5000 | resourceRetriever: com.nimbusds.jose.util.DefaultResourceRetr
iever@535d6e4c | responseType: id_token | responseMode: form_post | logoutUrl: null | withState: false | stateGenerator: org.pac4j.core.util.generator.RandomValueGenerator@67214
e | logoutHandler: #DefaultLogoutHandler# | store: #GuavaStore# | size: 10000 | timeout: 30 | timeUnit: MINUTES | | destroySession: false | | tokenValidator: null | |           
play   | [debug] o.p.o.c.e.OidcExtractor - Authentication response successful                                                                                                    
play   | [debug] o.p.o.c.OidcClient - Credentials validation took: 0 ms                                                                                                          
play   | [debug] o.p.o.c.OidcClient - clean authentication attempt                                                                                                               
play   | [debug] o.p.p.s.PlayCookieSessionStore - set key: OidcClient$attemptedAuthentication, with value: null                                                                  
play   | [trace] o.p.p.s.PlayCookieSessionStore - serialized token size = 172                                                                                                    
play   | [debug] o.p.c.e.DefaultCallbackLogic - credentials: Optional[#OidcCredentials# | code: null | accessToken: null | refreshToken: null | idToken: com.nimbusds.jwt.SignedJ
WT@32bdfafc |]                                                                                                                                                                   
play   | [debug] o.p.o.c.OidcClient - credentials : #OidcCredentials# | code: null | accessToken: null | refreshToken: null | idToken: com.nimbusds.jwt.SignedJWT@32bdfafc |     
play   | [debug] o.p.c.u.InitializableObject - Initializing: OidcProfileCreator                                                                                                  
play   | [debug] o.p.o.p.OidcProfile - adding => key: id_token / value: <snipped for length, but it decodes to a valid token> / class java.lang.String                                                                             
play   | [debug] o.p.p.s.PlayCookieSessionStore - Get value: null for key: OidcClient$nonceSessionParameter                                                                      
play   | [error] p.a.h.DefaultHttpErrorHandler -                                                                                                                                 
play   | 
play   | ! @7j1ha66ee - Internal server error, for (POST) [/callback/OidcClient] ->
play   |  
play   | play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[CompletionException: java.lang.IllegalArgumentException: The value must not be null or empty string.
...
play   | Caused by: java.lang.IllegalArgumentException: The value must not be null or empty string                                                                               
play   |        at com.nimbusds.oauth2.sdk.id.Identifier.<init>(Identifier.java:92)                                                                                              
play   |        at com.nimbusds.openid.connect.sdk.Nonce.<init>(Nonce.java:55)                                                                                                   
play   |        at org.pac4j.oidc.profile.creator.OidcProfileCreator.create(OidcProfileCreator.java:84)                                                                          
play   |        at org.pac4j.core.client.BaseClient.retrieveUserProfile(BaseClient.java:126)                                                                                     play   |        at org.pac4j.core.client.BaseClient.getUserProfile(BaseClient.java:105)                                                                                          
play   |        at org.pac4j.core.engine.DefaultCallbackLogic.perform(DefaultCallbackLogic.java:79)                                                                              
play   |        at org.pac4j.play.CallbackController.lambda$callback$0(CallbackController.java:53)                                                                               
play   |        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)                                                                 
play   |        at play.core.j.HttpExecutionContext.$anonfun$execute$1(HttpExecutionContext.scala:64)                                                                            
play   |        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
```

The crucial lines are
```
play   | [debug] o.p.p.s.PlayCookieSessionStore - set key: OidcClient$nonceSessionParameter, with value: 3CTD9eQkxQ8B_rEQ3nmqlsFCeuM0Dx9xWCWyc1WSEog                             
...
play   | [debug] o.p.p.s.PlayCookieSessionStore - Get value: null for key: OidcClient$nonceSessionParameter                                                                      
```

Which happens because the cookie is gone when I return to the redirect.  I think the 302 must be destroying it, somehow.

**Comment by ndmckinley** [comment]
The issue reproduces in http://play-pac4j-java-demo.herokuapp.com/.

Steps:
- Hit refresh on the main page, see that you have two cookies.
- Click the google OIDC login.  The OIDC login is misconfigured, but it doesn't matter.
- Hit back, return to the heroku app, and see that you have 0 cookies.

I'm trying to capture the response that I get, which I assume will be helpful...

**Comment by ndmckinley** [comment]
Hm.  Not obvious what the issue could be.

```
curl -v http://play-pac4j-java-demo.herokuapp.com/oidc/index.html
*   Trying 3.208.158.124...
* TCP_NODELAY set
* Connected to play-pac4j-java-demo.herokuapp.com (3.208.158.124) port 80 (#0)
> GET /oidc/index.html HTTP/1.1
> Host: play-pac4j-java-demo.herokuapp.com
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 302 Found
< Server: Cowboy
< Connection: keep-alive
< Pragma: no-cache
< Expires: 0
< Location: https://accounts.google.com/o/oauth2/v2/auth?scope=openid+profile+email&response_type=code&redirect_uri=https%3A%2F%2Fplay-pac4j-java-demo.herokuapp.com%2Fcallback%3Fclient_name%3DOidcClient&state=186c2b58d2&code_challenge_method=S256&prompt=consent&client_id=343992089165-i1es0qvej18asl33mvlbeq750i3ko32k.apps.googleusercontent.com&code_challenge=EdTX1IDfCU-RYqWZR2tNpuc218CWMSRJ892fzSl_3lk
< Set-Cookie: PLAY_SESSION=eyJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7InBhYzRqU2Vzc2lvbklkIjoiZGQxYjIyNzItMDc4NC00MGU4LWFkY2YtZjZmNWU2YmJjYjQyIn0sIm5iZiI6MTYxNDk3NDMwOCwiaWF0IjoxNjE0OTc0MzA4fQ.172v8brSm88NnpiTrFOnBQ6Sygg0ay2w-L8Z21ZcH0A; Path=/; HTTPOnly
< Set-Cookie: pac4jCsrfToken=d12a5db76f6d46bea926a681e2b793bd; Path=/; Domain=play-pac4j-java-demo.herokuapp.com
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< X-Frame-Options: DENY
< X-Xss-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< Date: Fri, 05 Mar 2021 19:58:28 GMT
< Content-Length: 0
< Via: 1.1 vegur
< 
* Connection #0 to host play-pac4j-java-demo.herokuapp.com left intact
* Closing connection 0
```

Contains everything it ought to... Huh.

**Comment by ndmckinley** [comment]
Issue solved.

It turns out the issue was that I was setting `samesite: Lax` on this cookie, because that's the default in Play 2.8.  Since I'm using the `form_post` response type, the cookie wasn't getting sent.

I addressed it by setting `play.http.session.sameSite = null`.  The cookie is getting sent now.

This is counter to what the Mozilla documentation says will happen, but, well, whatever.

**Comment by ndmckinley** [comment]
And it turns out that the "repro" I erroneously thought I was seeing in the demo app is actually just a misunderstanding on my part of which cookies Chrome displays to you.  Since I was hitting "back", to navigate away from an error page, Chrome didn't actually send any cookies on that request.  Which means it showed me a "0 active cookies" message.  That message is the number of cookies *sent* on the last request, *not* the number of cookies *stored* for a domain.

**Comment by leleuj** [comment]
Please use the mailing lists for questions.
